import { LIMITS } from '../../config/settings';
import { asFiniteNumberOrNull, asString, isRecord } from '../../lib/storage';
import type { Product, QuoteItem, QuoteItemSnapshot, StoredQuoteItem } from '../../types';
import { getPublicPrice, toStorefrontProduct } from '../catalog/pricing';

/** Ids generated by the configurator, warranty lookup and chat before Baseline v1. */
const CUSTOM_ID_PREFIXES = ['prod-custom-', 'prod-renewal-', 'prod-rfq-chat-', 'custom-'];

export function isCustomItemId(productId: string): boolean {
  return CUSTOM_ID_PREFIXES.some(prefix => productId.startsWith(prefix));
}

/** Clamp a requested quantity to a whole number within the allowed range. */
export function normalizeQuoteQuantity(value: unknown): number {
  const n = typeof value === 'number' ? value : Number(value);
  if (!Number.isFinite(n)) return LIMITS.quoteQtyMin;
  return Math.min(LIMITS.quoteQtyMax, Math.max(LIMITS.quoteQtyMin, Math.floor(n)));
}

/** Snapshot kept for display if the product later disappears. Contains no price, cost or stock. */
export function snapshotOf(product: Product): QuoteItemSnapshot {
  return {
    model: product.model,
    name: product.name,
    brand: product.brand,
    category: product.category,
    sku: product.sku,
    shortDescription: product.shortDescription,
    specifications: product.specifications.map(s => ({ ...s })),
  };
}

export function createStoredQuoteItem(product: Product, quantity: number, source: 'catalog' | 'custom'): StoredQuoteItem {
  return { productId: product.id, quantity: normalizeQuoteQuantity(quantity), source, snapshot: snapshotOf(product) };
}

/**
 * Normalise one persisted quote entry. Accepts the pre-baseline format
 * `{ productId, product, quantity }` (which stored a full product copy,
 * including any hidden price) and converts it to the price-free format.
 */
export function normalizeStoredQuoteItem(raw: unknown): StoredQuoteItem | null {
  if (!isRecord(raw)) return null;
  const productId = asString(raw.productId);
  if (!productId) return null;
  const quantity = normalizeQuoteQuantity(asFiniteNumberOrNull(raw.quantity) ?? 1);

  const source: 'catalog' | 'custom' =
    raw.source === 'custom' || raw.source === 'catalog' ? raw.source : isCustomItemId(productId) ? 'custom' : 'catalog';

  const snapRaw = isRecord(raw.snapshot) ? raw.snapshot : isRecord(raw.product) ? raw.product : {};
  const snapshot: QuoteItemSnapshot = {
    model: asString(snapRaw.model, 'Unnamed item'),
    name: asString(snapRaw.name, asString(snapRaw.model, 'Unnamed item')),
    brand: asString(snapRaw.brand),
    category: asString(snapRaw.category),
    sku: asString(snapRaw.sku),
    shortDescription: asString(snapRaw.shortDescription),
    specifications: Array.isArray(snapRaw.specifications)
      ? snapRaw.specifications.filter(isRecord).map(s => ({ key: asString(s.key), value: asString(s.value) }))
      : [],
  };
  return { productId, quantity, source, snapshot };
}

function productFromSnapshot(item: StoredQuoteItem): Product {
  const now = new Date().toISOString();
  return {
    id: item.productId,
    model: item.snapshot.model,
    name: item.snapshot.name,
    brand: item.snapshot.brand,
    category: item.snapshot.category,
    sku: item.snapshot.sku,
    shortDescription: item.snapshot.shortDescription,
    description: item.snapshot.shortDescription,
    specifications: item.snapshot.specifications,
    images: [],
    price: null,
    isPricePublic: false,
    stock: null,
    isPublished: true,
    isArchived: false,
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Resolve stored quote entries against the live catalogue. Catalogue items use
 * the current storefront-safe product (so prices are always current and never
 * hidden ones). Missing catalogue items and custom requests are shown from
 * their snapshot with no price.
 */
export function resolveQuoteItems(stored: StoredQuoteItem[], storefrontProducts: Product[]): QuoteItem[] {
  const byId = new Map(storefrontProducts.map(p => [p.id, p]));
  return stored.map(item => {
    if (item.source === 'catalog') {
      const live = byId.get(item.productId);
      if (live) {
        return { productId: item.productId, quantity: item.quantity, source: 'catalog', product: toStorefrontProduct(live), isListed: true };
      }
      return { productId: item.productId, quantity: item.quantity, source: 'catalog', product: productFromSnapshot(item), isListed: false };
    }
    return { productId: item.productId, quantity: item.quantity, source: 'custom', product: productFromSnapshot(item), isListed: true };
  });
}

export interface QuoteTotals {
  totalUnits: number;
  lineCount: number;
  /** True only when every line has a public price. */
  allLinesPriced: boolean;
  pricedLineCount: number;
  /** Sum of public-priced lines only. Show as a total only when allLinesPriced. */
  pricedSubtotal: number;
}

export function computeQuoteTotals(items: QuoteItem[]): QuoteTotals {
  let pricedSubtotal = 0;
  let pricedLineCount = 0;
  for (const item of items) {
    const price = getPublicPrice(item.product);
    if (price !== null) {
      pricedSubtotal += price * item.quantity;
      pricedLineCount++;
    }
  }
  return {
    totalUnits: items.reduce((s, i) => s + i.quantity, 0),
    lineCount: items.length,
    allLinesPriced: items.length > 0 && pricedLineCount === items.length,
    pricedLineCount,
    pricedSubtotal,
  };
}
